# Generated by Django 3.0.3 on 2020-03-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keeperadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keeper',
            options={'ordering': ['lastname', 'firstname']},
        ),
        migrations.AlterField(
            model_name='keeper',
            name='birthdate',
            field=models.DateField(blank=True, max_length=50),
        ),
    ]
