# Generated by Django 3.0.3 on 2020-03-16 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keeperadmin', '0002_auto_20200312_0455'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('recording_date', models.DateField(blank=True, max_length=50)),
                ('minutes_played', models.IntegerField(blank=True)),
                ('goals_against', models.IntegerField(blank=True)),
                ('shots_on_goal', models.IntegerField(blank=True)),
                ('saves', models.IntegerField(blank=True)),
                ('total_passes', models.IntegerField(blank=True)),
                ('passes_right', models.IntegerField(blank=True)),
                ('passes_left', models.IntegerField(blank=True)),
                ('passes_successfull', models.IntegerField(blank=True)),
                ('keeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keeperadmin.Keeper')),
            ],
            options={
                'ordering': ['recording_date', 'keeper'],
            },
        ),
    ]
